version: 0.2

env:
  variables:
    REPO_URL: "${REPO_URL}"
    IMAGE_TAG: "${IMAGE_TAG}"

phases:
  install:
    commands:
      - echo Installing AWS CLI...
      - apt-get update -y
      - apt-get install -y awscli

  pre_build:
    commands:
      - echo "REPO_URL: $REPO_URL"
      - echo Logging in to Amazon ECR...
      - aws --region us-east-1 ecr get-login-password | docker login --username AWS --password-stdin $REPO_URL
      - echo Build started on `date`

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPO_URL:$IMAGE_TAG .
      - docker tag $REPO_URL:$IMAGE_TAG $REPO_URL:latest  # Tagging with 'latest' (optional)

  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker push $REPO_URL:$IMAGE_TAG
      - docker push $REPO_URL:latest  # Pushing the 'latest' tag (optional)
      - echo Writing imagedefinitions.json file...
      - printf '[{"name":"my-ecs-cluster-container","imageUri":"%s"}]' $REPO_URL:$IMAGE_TAG > imagedefinitions.json
      - echo Build and push completed on `date`

artifacts:
  files:
    - imagedefinitions.json
