version: 0.2

phases:
  install:
    commands:
      - echo "Hello World"
      - echo '[{"name":"my-container","imageUri":"example-repo-url:latest"}]' > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
